/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

/**
 *
 * @author yasmi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastrar = new javax.swing.JMenu();
        jMcadastrarCliente = new javax.swing.JMenuItem();
        jMcadastrarJogo = new javax.swing.JMenuItem();
        jMcadastrarLocacao = new javax.swing.JMenuItem();
        jMdeletar = new javax.swing.JMenu();
        jMdeletarCliente = new javax.swing.JMenuItem();
        jMdeletarJogo = new javax.swing.JMenuItem();
        jMdeletarLocacao = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMlistarCliente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMalterar = new javax.swing.JMenu();
        jMalterarCliente = new javax.swing.JMenuItem();
        jMalterarJogos = new javax.swing.JMenuItem();
        jMalterarLocacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("GameStation");

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setForeground(new java.awt.Color(51, 204, 0));

        Cadastrar.setText("Cadastrar");

        jMcadastrarCliente.setText("Cliente");
        jMcadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadastrarClienteActionPerformed(evt);
            }
        });
        Cadastrar.add(jMcadastrarCliente);

        jMcadastrarJogo.setText("Jogo");
        jMcadastrarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadastrarJogoActionPerformed(evt);
            }
        });
        Cadastrar.add(jMcadastrarJogo);

        jMcadastrarLocacao.setText("Locação");
        jMcadastrarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadastrarLocacaoActionPerformed(evt);
            }
        });
        Cadastrar.add(jMcadastrarLocacao);

        jMenuBar1.add(Cadastrar);

        jMdeletar.setText("Deletar");

        jMdeletarCliente.setText("Clientes");
        jMdeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdeletarClienteActionPerformed(evt);
            }
        });
        jMdeletar.add(jMdeletarCliente);

        jMdeletarJogo.setText("Jogos");
        jMdeletarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdeletarJogoActionPerformed(evt);
            }
        });
        jMdeletar.add(jMdeletarJogo);

        jMdeletarLocacao.setText("Locações");
        jMdeletarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdeletarLocacaoActionPerformed(evt);
            }
        });
        jMdeletar.add(jMdeletarLocacao);

        jMenuBar1.add(jMdeletar);

        jMenu1.setText("Relatório");

        jMlistarCliente.setText("Clientes");
        jMlistarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMlistarCliente);

        jMenuItem2.setText("Jogos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Locações");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMalterar.setText("Alterar");

        jMalterarCliente.setText("Clientes");
        jMalterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterarClienteActionPerformed(evt);
            }
        });
        jMalterar.add(jMalterarCliente);

        jMalterarJogos.setText("Jogos");
        jMalterarJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterarJogosActionPerformed(evt);
            }
        });
        jMalterar.add(jMalterarJogos);

        jMalterarLocacao.setText("Locações");
        jMalterarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterarLocacaoActionPerformed(evt);
            }
        });
        jMalterar.add(jMalterarLocacao);

        jMenuBar1.add(jMalterar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMdeletarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdeletarJogoActionPerformed
        // TODO add your handling code here:
        FormDeletarJogo dj = new FormDeletarJogo();
        dj.show();
    }//GEN-LAST:event_jMdeletarJogoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormListarJogo lj = new FormListarJogo();
        lj.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMalterarJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterarJogosActionPerformed
        // TODO add your handling code here:
        FormAlterarJogo aj = new FormAlterarJogo();
        aj.show();
    }//GEN-LAST:event_jMalterarJogosActionPerformed

    private void jMdeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdeletarClienteActionPerformed
        // TODO add your handling code here:
        FormDeletarCliente dc = new FormDeletarCliente();
        dc.show();
    }//GEN-LAST:event_jMdeletarClienteActionPerformed

    private void jMcadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadastrarClienteActionPerformed
        // TODO add your handling code here:
        CadastroCliente cc = new CadastroCliente();
        cc.show();
    }//GEN-LAST:event_jMcadastrarClienteActionPerformed

    private void jMcadastrarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadastrarJogoActionPerformed
        // TODO add your handling code here:
        CadastrarJogo cj = new CadastrarJogo();
        cj.show();
    }//GEN-LAST:event_jMcadastrarJogoActionPerformed

    private void jMcadastrarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadastrarLocacaoActionPerformed
        // TODO add your handling code here:
        CadastroLocacao cl = new CadastroLocacao();
        cl.show();
    }//GEN-LAST:event_jMcadastrarLocacaoActionPerformed

    private void jMdeletarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdeletarLocacaoActionPerformed
        // TODO add your handling code here:
        FormDeletarLocacao dl = new FormDeletarLocacao();
        dl.show();
    }//GEN-LAST:event_jMdeletarLocacaoActionPerformed

    private void jMlistarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistarClienteActionPerformed
        // TODO add your handling code here:
        FormListarCliente lc = new FormListarCliente();
        lc.show();
    }//GEN-LAST:event_jMlistarClienteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FormListarLocacao ll = new FormListarLocacao();
        ll.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMalterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterarClienteActionPerformed
        // TODO add your handling code here:
        FormAlterarCliente ac = new FormAlterarCliente();
        ac.show();
    }//GEN-LAST:event_jMalterarClienteActionPerformed

    private void jMalterarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterarLocacaoActionPerformed
        // TODO add your handling code here:
        FormAlterarLocacao al = new FormAlterarLocacao();
        al.show();
    }//GEN-LAST:event_jMalterarLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMalterar;
    private javax.swing.JMenuItem jMalterarCliente;
    private javax.swing.JMenuItem jMalterarJogos;
    private javax.swing.JMenuItem jMalterarLocacao;
    private javax.swing.JMenuItem jMcadastrarCliente;
    private javax.swing.JMenuItem jMcadastrarJogo;
    private javax.swing.JMenuItem jMcadastrarLocacao;
    private javax.swing.JMenu jMdeletar;
    private javax.swing.JMenuItem jMdeletarCliente;
    private javax.swing.JMenuItem jMdeletarJogo;
    private javax.swing.JMenuItem jMdeletarLocacao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMlistarCliente;
    // End of variables declaration//GEN-END:variables
}
